Test #2: Trigger publishing to TestPyPI

diff --git a/.github/workflows/version.yml b/.github/workflows/version.yml
--- a/.github/workflows/version.yml
+++ b/.github/workflows/version.yml
@@ -36,12 +36,12 @@ jobs:
           else
             echo "New version is invalid."; exit 1
           fi
-      - name: Check development version validity
-        if: github.event.pull_request.base.ref != 'master'
-        run: |
-          pattern=^\(0\|[1-9][0-9]*\)\.\(0\|[1-9][0-9]*\)dev\(0\|[1-9][0-9]*\)$
-          if [[ ${{ env.new_version }} =~ $pattern ]]; then
-            echo "New version is valid."; exit 0
-          else
-            echo "New version is invalid."; exit 1
-          fi
+      # - name: Check development version validity
+      #   if: github.event.pull_request.base.ref != 'master'
+      #   run: |
+      #     pattern=^\(0\|[1-9][0-9]*\)\.\(0\|[1-9][0-9]*\)dev\(0\|[1-9][0-9]*\)$
+      #     if [[ ${{ env.new_version }} =~ $pattern ]]; then
+      #       echo "New version is valid."; exit 0
+      #     else
+      #       echo "New version is invalid."; exit 1
+      #     fi
